points:
  zones:  # Area that can be defined 
    main: # Defining Functional portions of the keyboard, letters & numbers
      columns:
        outer:
          rows.num.skip: true
          key:
        pinky:
          key:
            spread: cx 
        ring:
          key:
            stagger: 4
            spread: cx 
        middle:
          key:
            stagger: 2
            spread: cx 
        index:
          key:
            stagger: -2
            spread: cx 
        inner:
          key:
            stagger: -2
            spread: cx 
      rows:
        bottom:
        middle:
        top:
        num:
    thumb: # Created Thumb Cluster as own zone with two keys
      anchor:
        ref: main_index_bottom
        shift: [0,-20]
      rows:
      columns:
        inner:
        outer:
          key:
            spread: cx 
  mirror: &mirror 
      ref: main_inner_num 
      distance: 2.5cx

