units:
  px: cx + 2 # 20mm
  py: cy + 2 # 19mm

  pushX: (cx / 2) # 10mm
  pushY: (cy / 2) # 9.5

  padX: pushX + 2 # 12mm
  padY: pushY + 2 # 11.5mm

  pad: 2

points:
  zones: # Area that can be defined
    main: # Defining Functional portions of the keyboard, letters & numbers
      anchor: # Move to fit inside kiCAD sheet
        shift: [100, -150]
      columns:
        outer:
          rows.num.skip: true # ESC key hard to reach, placement for microcontroller
          key.column_net: P0
        pinky:
          key:
            spread: cx
            column_net: P1
        ring:
          key:
            stagger: 8
            spread: cx
            column_net: P2
        middle:
          key:
            stagger: 2
            spread: cx
            column_net: P3
        index:
          key:
            stagger: -2
            spread: cx
            column_net: P4
        inner:
          key:
            stagger: -2
            spread: cx
            column_net: P5
      rows:
        bottom:
          row_net: P7
        middle:
          row_net: P8
        top:
          row_net: P9
        num:
          row_net: P10
    thumb: # Created Thumb Cluster as own zone with two keys
      anchor:
        ref: main_index_bottom
        shift: [0, -20]
      columns:
        inner:
          key.column_net: P3
        middle:
          key:
            spread: cx
            column_net: P4
        outer:
          key:
            spread: cx
            column_net: P5
      rows:
        cluster:
          row_net: P6
  mirror: &mirror
    ref: main_inner_num
    distance: 5cx

outlines:
  raw:
    - what: rectangle
      where: true
      size: [px, py]
  keys:
    - what: rectangle
      where: true
      size: [cx-0.5, cy-0.5]
  board_left:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: main_inner_num
          shift: [padX -pad + px, 0]
        - ref: thumb_outer_cluster
          shift: [-pushX + px, -pushX-pad]
        - ref: main_outer_bottom
          shift: [pushX, -py-pad*2]
        - ref: main_outer_bottom
          shift: [-pushX-pad*2, -py+pushY]
        - ref: main_outer_top
          shift: [-padX-pad-1, px +py-pad+2]
        - ref: main_pinky_num
          shift: [0, px]
        - ref: main_middle_num
          shift: [0, px/2]
        - ref: main_inner_num
          shift: [padX, px-6]
  board_right:
    - what: polygon
      operation: stack
      points:
        - ref: mirror_main_inner_num
          shift: [padX -pad + px, 0]
        - ref: mirror_thumb_outer_cluster
          shift: [-pushX + px, -pushX-pad]
        - ref: mirror_main_outer_bottom
          shift: [pushX, -py-pad*2]
        - ref: mirror_main_outer_bottom
          shift: [-pushX-pad*2, -py+pushY]
        - ref: mirror_main_outer_top
          shift: [-padX-pad-1, px +py-pad+2]
        - ref: mirror_main_pinky_num
          shift: [0, px]
        - ref: mirror_main_middle_num
          shift: [0, px/2]
        - ref: mirror_main_inner_num
          shift: [padX, px-6]
      fillet: 2
  cutout_left:
    - name: board_left
    - operation: subtract
      name: keys
pcbs:
  left:
    outlines:
      main:
        outline: board_left
    footprints:
      choc_hotswap:
        what: choc
        where: /^(?!mirror_thumb)(main_|thumb_).*/
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: /^(?!mirror_thumb)(main_|thumb_).*/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      # Controller
      controller:
        what: xiao-ble
        where:
          ref: main_outer_top
          shift: [-1, 25]
          rotate: 90
      # JST Connector, Connected
      jstph:
        what: jstph
        where:
          ref: main_outer_bottom
          shift: [20, -15]
          rotate: 90
        params:
          pos: BAT+
          neg: GND
      # Battery Switch,
      battery_switch:
        what: slider
        where:
          ref: main_inner_num
          shift: [27, -5]
          rotate: -90
        params:
          from: BAT+
          to: GND
      #Reset , Connected
      reset:
        what: EVQPUC
        params:
          from: GND
          to: RST
        where:
          ref: main_inner_num
          shift: [27, -15]
          rotate: -90
      # Mounting Holes
      hole_top_left:
        what: mountinghole
        where:
          ref: main_pinky_num
          shift: [0, 17.5]
      hole_bottom_left:
        what: mountinghole
        where:
          ref: main_outer_bottom
          shift: [10, -20.5]
      hole_top_right:
        what: mountinghole
        where:
          ref: main_inner_num
          shift: [10, 11.5]
      hole_bottom_right:
        what: mountinghole
        where:
          ref: main_inner_bottom
          shift: [26.5, -5]
  right:
    outlines:
      main:
        outline: board_right
    footprints:
      choc_hotswap:
        what: choc
        where: /^mirror.*/
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: /^mirror.*/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      # Controller
      controller:
        what: testfootprint
        where:
          ref: mirror_main_outer_top
          shift: [-2, 25]
          rotate: 90
      # JST Connector, Connected
      jstph:
        what: jstph
        where:
          ref: mirror_main_outer_bottom
          shift: [20, -15]
          rotate: 90
        params:
          pos: BAT+
          neg: GND
      # Battery Switch,
      battery_switch:
        what: slider
        where:
          ref: mirror_main_inner_num
          shift: [27, -5]
          rotate: -90
        params:
          from: BAT+
          to: GND
      #Reset , Connected
      reset:
        what: EVQPUC
        params:
          from: GND
          to: RST
        where:
          ref: mirror_main_inner_num
          shift: [26.5, -15]
          rotate: -90
      # Mounting Holes
      hole_top_left:
        what: mountinghole
        where:
          ref: mirror_main_pinky_num
          shift: [0, 17]
      hole_bottom_left:
        what: mountinghole
        where:
          ref: mirror_main_outer_bottom
          shift: [10, -20]
      hole_top_right:
        what: mountinghole
        where:
          ref: mirror_main_inner_num
          shift: [10, 11]
      hole_bottom_right:
        what: mountinghole
        where:
          ref: mirror_main_inner_bottom
          shift: [26.5, -5]
